In [3]:
import pandas as pd
import numpy as np

### Soal no 1

In [4]:
df = pd.read_excel(r"C:\Users\Adi\Downloads\Dataset grup A.xlsx") ### file tergantung dari user
df

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm)
0,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159
1,DS5A02,Rahmi Najla,Informatika,53,156
2,DS5A03,Wafiq Azizah,Sistem Informasi,40,154
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170
4,DS5A05,Icha Patricia,Informatika,55,157
5,DS5A06,Nurhasanah,Teknik Informatika,60,160
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155
9,DS5A10,Nuril Alim Abidin,Fisika,74,173
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154
11,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168
13,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160
14,DS5A15,Asima Manalu,Statistika,56,165
15,DS5A16,Oxana Fedorova,Informatika,43,150
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178
17,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179
18,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160
19,DS5A20,Nurul Lailia,Informatika,36,151
20,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164
22,DS5A23,Erda Putriana,Informatika,55,166
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158

### Soal no 2

In [5]:
BMI = df['Berat Badan (kg)'] / ((df['Tinggi Badan (cm)']/100) ** 2)

### Soal no 3

In [6]:
for BMI in df:
    BMI = df['Berat Badan (kg)'] / ((df['Tinggi Badan (cm)']/100) ** 2)
print(BMI)

0     17.008821
1     21.778435
2     16.866251
3     23.529412
4     22.313278
5     23.437500
6     21.928863
7     20.449137
8     16.649324
9     24.725183
10    16.444594
11    20.449137
12    21.258503
13    23.828125
14    20.569330
15    19.111111
16    18.305769
17    22.783309
18    19.531250
19    15.788781
20    22.038567
21    18.590125
22    19.959355
23    22.031726
dtype: float64

### Soal no 4

In [8]:
df.insert(5, 'BMI', BMI)
df

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI
0,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159,17.008821
1,DS5A02,Rahmi Najla,Informatika,53,156,21.778435
2,DS5A03,Wafiq Azizah,Sistem Informasi,40,154,16.866251
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412
4,DS5A05,Icha Patricia,Informatika,55,157,22.313278
5,DS5A06,Nurhasanah,Teknik Informatika,60,160,23.437500
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151,21.928863
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164,20.449137
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155,16.649324
9,DS5A10,Nuril Alim Abidin,Fisika,74,173,24.725183
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154,16.444594
11,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164,20.449137
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168,21.258503
13,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160,23.828125
14,DS5A15,Asima Manalu,Statistika,56,165,20.569330
15,DS5A16,Oxana Fedorova,Informatika,43,150,19.111111
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769
17,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179,22.783309
18,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160,19.531250
19,DS5A20,Nurul Lailia,Informatika,36,151,15.788781
20,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165,22.038567
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164,18.590125
22,DS5A23,Erda Putriana,Informatika,55,166,19.959355
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158,22.031726

### Soal no 5

In [22]:
df['Status BMI'] = pd.cut(
    df['BMI'], bins=[0, 18, 24.9, 29.9, float('inf')],
    labels=['Underweight', 'Normal', 'Overweight', 'Obesity']
)
df

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159,17.008821,Underweight
1,DS5A02,Rahmi Najla,Informatika,53,156,21.778435,Normal
2,DS5A03,Wafiq Azizah,Sistem Informasi,40,154,16.866251,Underweight
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412,Normal
4,DS5A05,Icha Patricia,Informatika,55,157,22.313278,Normal
5,DS5A06,Nurhasanah,Teknik Informatika,60,160,23.437500,Normal
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151,21.928863,Normal
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164,20.449137,Normal
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155,16.649324,Underweight
9,DS5A10,Nuril Alim Abidin,Fisika,74,173,24.725183,Normal
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154,16.444594,Underweight
11,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164,20.449137,Normal
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168,21.258503,Normal
13,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160,23.828125,Normal
14,DS5A15,Asima Manalu,Statistika,56,165,20.569330,Normal
15,DS5A16,Oxana Fedorova,Informatika,43,150,19.111111,Normal
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769,Normal
17,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179,22.783309,Normal
18,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160,19.531250,Normal
19,DS5A20,Nurul Lailia,Informatika,36,151,15.788781,Underweight
20,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165,22.038567,Normal
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164,18.590125,Normal
22,DS5A23,Erda Putriana,Informatika,55,166,19.959355,Normal
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158,22.031726,Normal

### cara 2

In [21]:
df["Status BMI"] = ''

for i in range(len(df)):
  if df['BMI'][i] >= 18.5 and df['BMI'][i] <= 24.9:
    df["Status BMI"][i] = 'Normal'
  elif df['BMI'][i] >= 25 and df['BMI'][i] <= 29.9:
    df["Status BMI"][i] = 'Overweight'
  elif df['BMI'][i] >= 30 and df['BMI'][i] <= 34.9:
    df["Status BMI"][i] = 'Obesity'
  elif df['BMI'][i] < 18.5:
    df["Status BMI"][i] = 'Underweight'
  else:
    df["Status BMI"][i] = 'Error'
df

C:\Users\Adi\AppData\Local\Temp\ipykernel_3804\3774593372.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Status BMI"][i] = 'Underweight'
C:\Users\Adi\AppData\Local\Temp\ipykernel_3804\3774593372.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Status BMI"][i] = 'Normal'

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159,17.008821,Underweight
1,DS5A02,Rahmi Najla,Informatika,53,156,21.778435,Normal
2,DS5A03,Wafiq Azizah,Sistem Informasi,40,154,16.866251,Underweight
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412,Normal
4,DS5A05,Icha Patricia,Informatika,55,157,22.313278,Normal
5,DS5A06,Nurhasanah,Teknik Informatika,60,160,23.437500,Normal
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151,21.928863,Normal
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164,20.449137,Normal
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155,16.649324,Underweight
9,DS5A10,Nuril Alim Abidin,Fisika,74,173,24.725183,Normal
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154,16.444594,Underweight
11,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164,20.449137,Normal
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168,21.258503,Normal
13,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160,23.828125,Normal
14,DS5A15,Asima Manalu,Statistika,56,165,20.569330,Normal
15,DS5A16,Oxana Fedorova,Informatika,43,150,19.111111,Normal
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769,Underweight
17,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179,22.783309,Normal
18,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160,19.531250,Normal
19,DS5A20,Nurul Lailia,Informatika,36,151,15.788781,Underweight
20,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165,22.038567,Normal
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164,18.590125,Normal
22,DS5A23,Erda Putriana,Informatika,55,166,19.959355,Normal
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158,22.031726,Normal

### Soal no 6a

In [ ]:
df_sort_height = df.sort_values(by="Tinggi Badan (cm)", ascending=False) 
df_sort_height

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
17,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179,22.783309,Normal
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769,Normal
9,DS5A10,Nuril Alim Abidin,Fisika,74,173,24.725183,Normal
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412,Normal
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168,21.258503,Normal
22,DS5A23,Erda Putriana,Informatika,55,166,19.959355,Normal
14,DS5A15,Asima Manalu,Statistika,56,165,20.569330,Normal
20,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165,22.038567,Normal
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164,18.590125,Normal
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164,20.449137,Normal
11,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164,20.449137,Normal
5,DS5A06,Nurhasanah,Teknik Informatika,60,160,23.437500,Normal
18,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160,19.531250,Normal
13,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160,23.828125,Normal
0,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159,17.008821,Underweight
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158,22.031726,Normal
4,DS5A05,Icha Patricia,Informatika,55,157,22.313278,Normal
1,DS5A02,Rahmi Najla,Informatika,53,156,21.778435,Normal
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155,16.649324,Underweight
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154,16.444594,Underweight
2,DS5A03,Wafiq Azizah,Sistem Informasi,40,154,16.866251,Underweight
19,DS5A20,Nurul Lailia,Informatika,36,151,15.788781,Underweight
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151,21.928863,Normal
15,DS5A16,Oxana Fedorova,Informatika,43,150,19.111111,Normal

### Soal no 6b

In [ ]:
df_sort_name = df.sort_values(by="Nama", ascending=False) 
df_sort_name

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
2,DS5A03,Wafiq Azizah,Sistem Informasi,40,154,16.866251,Underweight
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769,Normal
18,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160,19.531250,Normal
13,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160,23.828125,Normal
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164,20.449137,Normal
1,DS5A02,Rahmi Najla,Informatika,53,156,21.778435,Normal
15,DS5A16,Oxana Fedorova,Informatika,43,150,19.111111,Normal
19,DS5A20,Nurul Lailia,Informatika,36,151,15.788781,Underweight
9,DS5A10,Nuril Alim Abidin,Fisika,74,173,24.725183,Normal
5,DS5A06,Nurhasanah,Teknik Informatika,60,160,23.437500,Normal
20,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165,22.038567,Normal
11,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164,20.449137,Normal
0,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159,17.008821,Underweight
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158,22.031726,Normal
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151,21.928863,Normal
4,DS5A05,Icha Patricia,Informatika,55,157,22.313278,Normal
17,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179,22.783309,Normal
22,DS5A23,Erda Putriana,Informatika,55,166,19.959355,Normal
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155,16.649324,Underweight
14,DS5A15,Asima Manalu,Statistika,56,165,20.569330,Normal
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164,18.590125,Normal
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412,Normal
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154,16.444594,Underweight
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168,21.258503,Normal

### Soal no 7a

In [ ]:
df[df["BMI"] > 24.9]

Empty DataFrame
Columns: [No. Peserta, Nama, Jurusan, Berat Badan (kg), Tinggi Badan (cm), BMI, Status BMI]
Index: []

### Soal no 7b

In [ ]:
df[df["Berat Badan (kg)"] > 60]
df[df["Tinggi Badan (cm)"] > 169]

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412,Normal
9,DS5A10,Nuril Alim Abidin,Fisika,74,173,24.725183,Normal
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769,Normal
17,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179,22.783309,Normal

### Soal no 7c

In [ ]:
df[df["Nama"].str.contains('y')]

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412,Normal
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151,21.928863,Normal
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164,20.449137,Normal
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155,16.649324,Underweight
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154,16.444594,Underweight
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168,21.258503,Normal
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769,Normal
20,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165,22.038567,Normal
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164,18.590125,Normal
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158,22.031726,Normal

### Soal no 7d

In [ ]:
df[df["Berat Badan (kg)"] < 60]

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159,17.008821,Underweight
1,DS5A02,Rahmi Najla,Informatika,53,156,21.778435,Normal
2,DS5A03,Wafiq Azizah,Sistem Informasi,40,154,16.866251,Underweight
4,DS5A05,Icha Patricia,Informatika,55,157,22.313278,Normal
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151,21.928863,Normal
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164,20.449137,Normal
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155,16.649324,Underweight
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154,16.444594,Underweight
11,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164,20.449137,Normal
14,DS5A15,Asima Manalu,Statistika,56,165,20.569330,Normal
15,DS5A16,Oxana Fedorova,Informatika,43,150,19.111111,Normal
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769,Normal
18,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160,19.531250,Normal
19,DS5A20,Nurul Lailia,Informatika,36,151,15.788781,Underweight
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164,18.590125,Normal
22,DS5A23,Erda Putriana,Informatika,55,166,19.959355,Normal
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158,22.031726,Normal

### Soal no 8

In [ ]:
Nomor_Urut = range(1, len(df) + 1)
df.insert(0, "No.", Nomor_Urut)
df

,No.,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,1,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159,17.008821,Underweight
1,2,DS5A02,Rahmi Najla,Informatika,53,156,21.778435,Normal
2,3,DS5A03,Wafiq Azizah,Sistem Informasi,40,154,16.866251,Underweight
3,4,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412,Normal
4,5,DS5A05,Icha Patricia,Informatika,55,157,22.313278,Normal
5,6,DS5A06,Nurhasanah,Teknik Informatika,60,160,23.437500,Normal
6,7,DS5A07,Ismatu Laila Syifa',Matematika,50,151,21.928863,Normal
7,8,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164,20.449137,Normal
8,9,DS5A09,Dewi Ayati,Sistem Informasi,40,155,16.649324,Underweight
9,10,DS5A10,Nuril Alim Abidin,Fisika,74,173,24.725183,Normal
10,11,DS5A11,Aisyah Hayya Imani,Informatika,39,154,16.444594,Underweight
11,12,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164,20.449137,Normal
12,13,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168,21.258503,Normal
13,14,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160,23.828125,Normal
14,15,DS5A15,Asima Manalu,Statistika,56,165,20.569330,Normal
15,16,DS5A16,Oxana Fedorova,Informatika,43,150,19.111111,Normal
16,17,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178,18.305769,Normal
17,18,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179,22.783309,Normal
18,19,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160,19.531250,Normal
19,20,DS5A20,Nurul Lailia,Informatika,36,151,15.788781,Underweight
20,21,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165,22.038567,Normal
21,22,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164,18.590125,Normal
22,23,DS5A23,Erda Putriana,Informatika,55,166,19.959355,Normal
23,24,DS5A24,Mentari Murhabilasyah,Kimia,55,158,22.031726,Normal

### Soal no 9a

In [ ]:
kelompok_tinggi = df.groupby('Tinggi Badan (cm)')
kelompok_tinggi

### Soal no 9 b

In [ ]:
df["Tinggi Badan (cm)"].mean()

161.70833333333334

### Soal no 9c

In [ ]:
df["Berat Badan (kg)"].mean()

53.708333333333336

### Soal no 9d

In [ ]:
len(df)

24

### Soal no 9e

In [ ]:
df.nlargest(5, 'BMI')

,No.,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
9,10,DS5A10,Nuril Alim Abidin,Fisika,74,173,24.725183,Normal
13,14,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160,23.828125,Normal
3,4,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170,23.529412,Normal
5,6,DS5A06,Nurhasanah,Teknik Informatika,60,160,23.437500,Normal
17,18,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179,22.783309,Normal

### Soal no 9f

In [ ]:
underweight = df[df['Status BMI'].str.contains('Underweight')]
normal = df[df['Status BMI'].str.contains('Normal')]
obesity = df[df['Status BMI'].str.contains('Obesity')]
overweight = df[df['Status BMI'].str.contains('Overweight')]

In [ ]:
jumlah_underweight = len(underweight)
print("jumlah_underweight:", jumlah_underweight)

jumlah_normal = len(normal)
print("jumlah_normal:", jumlah_normal)

jumlah_obesity = len(obesity)
print("jumlah_obesity:", jumlah_obesity)

jumlah_overweight = len(overweight)
print("jumlah_overweight:", jumlah_overweight)

jumlah_underweight: 5
jumlah_normal: 19
jumlah_obesity: 0
jumlah_overweight: 0