In [1]:
import pandas as pd
import numpy as np

### Soal no 1

In [49]:
df = pd.read_excel(r"C:\Users\Adi\Downloads\Dataset grup A.xlsx") ### file tergantung dari user

In [50]:
df

,No. Peserta,Nama,Jurusan,Berat Badan (kg),Tinggi Badan (cm)
0,DS5A01,Najla Atikah Dwirahma,Teknik Informatika,43,159
1,DS5A02,Rahmi Najla,Informatika,53,156
2,DS5A03,Wafiq Azizah,Sistem Informasi,40,154
3,DS5A04,Alamsyah Dwi Putra,Sistem dan Teknologi Informasi,68,170
4,DS5A05,Icha Patricia,Informatika,55,157
5,DS5A06,Nurhasanah,Teknik Informatika,60,160
6,DS5A07,Ismatu Laila Syifa',Matematika,50,151
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,Informatika,55,164
8,DS5A09,Dewi Ayati,Sistem Informasi,40,155
9,DS5A10,Nuril Alim Abidin,Fisika,74,173
10,DS5A11,Aisyah Hayya Imani,Informatika,39,154
11,DS5A12,Nanang Arifin,Ekonomi Pembangunan,55,164
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,Ilmu Ekonomi,60,168
13,DS5A14,Sinta Dwi Rosalia,Oseanografi,61,160
14,DS5A15,Asima Manalu,Statistika,56,165
15,DS5A16,Oxana Fedorova,Informatika,43,150
16,DS5A17,Vedly Vedliyan Darma Oktavian,Informatika,58,178
17,DS5A18,Febrian Chrissma Bagaskara,Informatika,73,179
18,DS5A19,Valencia Claudia Jennifer Kaunang,Sistem Informasi,50,160
19,DS5A20,Nurul Lailia,Informatika,36,151
20,DS5A21,Ni Putu Septiary Devi Saraswati,Sistem Informasi,60,165
21,DS5A22,Ananda Shafa Nurhayah,Pendidikan Bahasa Inggris,50,164
22,DS5A23,Erda Putriana,Informatika,55,166
23,DS5A24,Mentari Murhabilasyah,Kimia,55,158

### Soal no 2

### Soal no 3

In [76]:
for BMI in df:
    BMI = df['Berat Badan (kg)'] / (df['Tinggi Badan (cm)'] ** 2)
print(BMI)

0     0.001701
1     0.002178
2     0.001687
3     0.002353
4     0.002231
5     0.002344
6     0.002193
7     0.002045
8     0.001665
9     0.002473
10    0.001644
11    0.002045
12    0.002126
13    0.002383
14    0.002057
15    0.001911
16    0.001831
17    0.002278
18    0.001953
19    0.001579
20    0.002204
21    0.001859
22    0.001996
23    0.002203
dtype: float64

### Soal no 4

In [77]:
df['BMI'] = pd.DataFrame(BMI)
df.insert(5, 'BMI', BMI)
df

ValueError: cannot insert BMI, already exists

### Soal no 5

In [81]:
print(df.drop('5', axis=1))
df

   No. Peserta                                   Nama       BMI  \
0       DS5A01                  Najla Atikah Dwirahma  0.001701
1       DS5A02                            Rahmi Najla  0.002178
2       DS5A03                           Wafiq Azizah  0.001687
3       DS5A04                     Alamsyah Dwi Putra  0.002353
4       DS5A05                          Icha Patricia  0.002231
5       DS5A06                             Nurhasanah  0.002344
6       DS5A07                    Ismatu Laila Syifa'  0.002193
7       DS5A08  Shalli Dyangrosa Permatanurani Balqis  0.002045
8       DS5A09                             Dewi Ayati  0.001665
9       DS5A10                    Nuril Alim Abidin    0.002473
10      DS5A11                     Aisyah Hayya Imani  0.001644
11      DS5A12                          Nanang Arifin  0.002045
12      DS5A13   Abigail Dorothy Hertaruli Oppusunggu  0.002126
13      DS5A14                     Sinta Dwi Rosalia   0.002383
14      DS5A15                           Asima Manalu  0.002057
15      DS5A16                         Oxana Fedorova  0.001911
16      DS5A17          Vedly Vedliyan Darma Oktavian  0.001831
17      DS5A18            Febrian Chrissma Bagaskara   0.002278
18      DS5A19      Valencia Claudia Jennifer Kaunang  0.001953
19      DS5A20                           Nurul Lailia  0.001579
20      DS5A21        Ni Putu Septiary Devi Saraswati  0.002204
21      DS5A22                 Ananda Shafa Nurhayah   0.001859
22      DS5A23                          Erda Putriana  0.001996
23      DS5A24                  Mentari Murhabilasyah  0.002203

                           Jurusan  Berat Badan (kg)  Tinggi Badan (cm)
0               Teknik Informatika                43                159
1                      Informatika                53                156
2                 Sistem Informasi                40                154
3   Sistem dan Teknologi Informasi                68                170
4                      Informatika                55                157
5               Teknik Informatika                60                160
6                       Matematika                50                151
7                      Informatika                55                164
8                 Sistem Informasi                40                155
9                           Fisika                74                173
10                     Informatika                39                154
11             Ekonomi Pembangunan                55                164
12                    Ilmu Ekonomi                60                168
13                    Oseanografi                 61                160
14                      Statistika                56                165
15                     Informatika                43                150
16                     Informatika                58                178
17                    Informatika                 73                179
18                Sistem Informasi                50                160
19                     Informatika                36                151
20                Sistem Informasi                60                165
21      Pendidikan Bahasa Inggris                 50                164
22                     Informatika                55                166
23                           Kimia                55                158

,No. Peserta,Nama,5,BMI,Jurusan,Berat Badan (kg),Tinggi Badan (cm)
0,DS5A01,Najla Atikah Dwirahma,0.001701,0.001701,Teknik Informatika,43,159
1,DS5A02,Rahmi Najla,0.002178,0.002178,Informatika,53,156
2,DS5A03,Wafiq Azizah,0.001687,0.001687,Sistem Informasi,40,154
3,DS5A04,Alamsyah Dwi Putra,0.002353,0.002353,Sistem dan Teknologi Informasi,68,170
4,DS5A05,Icha Patricia,0.002231,0.002231,Informatika,55,157
5,DS5A06,Nurhasanah,0.002344,0.002344,Teknik Informatika,60,160
6,DS5A07,Ismatu Laila Syifa',0.002193,0.002193,Matematika,50,151
7,DS5A08,Shalli Dyangrosa Permatanurani Balqis,0.002045,0.002045,Informatika,55,164
8,DS5A09,Dewi Ayati,0.001665,0.001665,Sistem Informasi,40,155
9,DS5A10,Nuril Alim Abidin,0.002473,0.002473,Fisika,74,173
10,DS5A11,Aisyah Hayya Imani,0.001644,0.001644,Informatika,39,154
11,DS5A12,Nanang Arifin,0.002045,0.002045,Ekonomi Pembangunan,55,164
12,DS5A13,Abigail Dorothy Hertaruli Oppusunggu,0.002126,0.002126,Ilmu Ekonomi,60,168
13,DS5A14,Sinta Dwi Rosalia,0.002383,0.002383,Oseanografi,61,160
14,DS5A15,Asima Manalu,0.002057,0.002057,Statistika,56,165
15,DS5A16,Oxana Fedorova,0.001911,0.001911,Informatika,43,150
16,DS5A17,Vedly Vedliyan Darma Oktavian,0.001831,0.001831,Informatika,58,178
17,DS5A18,Febrian Chrissma Bagaskara,0.002278,0.002278,Informatika,73,179
18,DS5A19,Valencia Claudia Jennifer Kaunang,0.001953,0.001953,Sistem Informasi,50,160
19,DS5A20,Nurul Lailia,0.001579,0.001579,Informatika,36,151
20,DS5A21,Ni Putu Septiary Devi Saraswati,0.002204,0.002204,Sistem Informasi,60,165
21,DS5A22,Ananda Shafa Nurhayah,0.001859,0.001859,Pendidikan Bahasa Inggris,50,164
22,DS5A23,Erda Putriana,0.001996,0.001996,Informatika,55,166
23,DS5A24,Mentari Murhabilasyah,0.002203,0.002203,Kimia,55,158